"""Initial document review schema"""

import sqlalchemy as sa
from alembic import op

revision = "9b9eb6571ac7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("heartbeat", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("ignored", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("started", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "pair_codes",
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "routes",
        sa.Column("property", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("property", "year"),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("csrf", sa.String(), nullable=False),
        sa.Column("expires", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "upload_receipts",
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("document_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidates_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidates_status"), ["status"], unique=False)

    op.create_table(
        "extraction_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extraction_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extraction_attempts_document_id"), ["document_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.Integer(), nullable=False),
        sa.Column("claim", sa.String(), nullable=True),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "pages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pages_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pages_sha256"), ["sha256"], unique=False)

    op.create_table(
        "archive_receipts",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("page_id", sa.String(), nullable=False),
        sa.Column("received", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("device_id", "page_id"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_candidate_id"), ["candidate_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_candidate_id"))

    op.drop_table("audit")
    op.drop_table("archive_receipts")
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pages_sha256"))
        batch_op.drop_index(batch_op.f("ix_pages_document_id"))

    op.drop_table("pages")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_document_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("extraction_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_attempts_document_id"))

    op.drop_table("extraction_attempts")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_status"))
        batch_op.drop_index(batch_op.f("ix_candidates_document_id"))

    op.drop_table("candidates")
    op.drop_table("users")
    op.drop_table("upload_receipts")
    op.drop_table("settings")
    op.drop_table("sessions")
    op.drop_table("routes")
    op.drop_table("pair_codes")
    op.drop_table("login_attempts")
    op.drop_table("documents")
    op.drop_table("devices")
    # ### end Alembic commands ###
